apply plugin: 'com.android.library'

android {

    compileSdkVersion 35
    namespace "xcrash.lib"
    
    defaultConfig {
        minSdkVersion 28
        consumerProguardFiles 'proguard-rules.pro'
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
    
    ndkPath System.getenv('ANDROID_NDK_HOME')
    ndkVersion "29.0.14206865"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}