buildscript {
    repositories {
    	google()
    	mavenCentral()
    	maven { url 'https://jitpack.io' }
    }
    dependencies { classpath 'com.android.tools.build:gradle:8.7.0' }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

apply plugin: 'com.android.application'

android {
    namespace 'com.sbmatch.androlua'
    compileSdk 35
    
    defaultConfig {
        applicationId "com.sbmatch.androlua"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
        
        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }
        
        externalNativeBuild {
            ndkBuild {
               abiFilters 'arm64-v8a', 'x86_64'
               arguments "NDK_LIBS_OUT=src/main/jniLibs"
            }
        }
    
    }

    ndkPath System.getenv('ANDROID_NDK_HOME')
    ndkVersion "29.0.14206865"

    externalNativeBuild {
        ndkBuild {
            path = file('jni/Android.mk')
        }
    }
    
    signingConfigs {
        release {
            storeFile file(System.getenv('KEYSTORE_PATH') ?: System.getenv('HOME') + "/.android/debug.keystore")
            storePassword System.getenv('KEYSTORE_PASSWORD') ?: "android"
            keyAlias System.getenv('KEY_ALIAS') ?: "androiddebugkey"
            keyPassword System.getenv('KEY_PASSWORD') ?: "android"
            enableV2Signing true
            enableV3Signing true
        }
    }

    buildTypes {
        release {
            minifyEnabled true          // 启用混淆
            shrinkResources true        // 启用资源压缩
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        
        debug {
            minifyEnabled false
            shrinkResources false
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main{
            jniLibs.srcDirs = ['libs']
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
    
    applicationVariants.all { variant ->
        // 遍历所有的变体
        variant.outputs.all {
            // 获取应用的版本名
            def versionName = variant.versionName
            def versionCode = getDefaultConfig().versionCode
            
            outputFileName = "androlua_v${versionName}.apk"
        }
    }
    
    dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])
    	implementation 'androidx.appcompat:appcompat:1.6.1'
    	implementation 'com.google.android.material:material:1.9.0'
    	implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    	implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    	
    	implementation 'com.github.kongzue:BaseFramework:latest.release'
    	implementation 'commons-io:commons-io:2.22.0'
    	
    	implementation project(':xcrash_lib')
    	implementation 'com.tencent:mmkv:2.4.1'
    }
}
