LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_C_INCLUDES += $(LOCAL_PATH)/../lua
LOCAL_MODULE     := luajava
LOCAL_SRC_FILES  := luajava.c
LOCAL_STATIC_LIBRARIES := liblua
LOCAL_CFLAGS     += -DLUA_COMPAT_5_3 
LOCAL_LDFLAGS += -Wl,-E
include $(BUILD_SHARED_LIBRARY)
